// SPDX-FileCopyrightText: 2026 Janet Blackquill <uhhadd@gmail.com>
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.Mind;
using Content.Shared.Roles.Jobs;
using Content.Client.Goals;
using Content.Shared.Goals;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Character;

[GenerateTypedNameReferences]
public sealed partial class StellarCharacterWindow : FancyWindow
{
    [Dependency] private IPlayerManager _player = default!;
    [Dependency] private IPrototypeManager _prototype = default!;
    [Dependency] private IEntityManager _entity = default!;

    private readonly SharedJobSystem _job;
    private readonly SharedMindSystem _mind;
    private readonly SpriteSystem _sprite;
    private readonly StellarClientGoalsSystem _clientGoals;
    private readonly StellarGoalsSystem _goals;

    public StellarCharacterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _job = _entity.System<SharedJobSystem>();
        _mind = _entity.System<SharedMindSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _clientGoals = _entity.System<StellarClientGoalsSystem>();
        _goals = _entity.System<StellarGoalsSystem>();

        Update();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _player.LocalPlayerAttached += LocalPlayerAttached;
        _clientGoals.OnContainerChanged += OnContainerChanged;
        _clientGoals.OnObserverChanged += OnObserverChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _player.LocalPlayerAttached -= LocalPlayerAttached;
        _clientGoals.OnContainerChanged -= OnContainerChanged;
        _clientGoals.OnObserverChanged -= OnObserverChanged;
    }

    private void OnContainerChanged(Entity<StellarGoalContainerComponent> container)
    {
        if (_player.LocalEntity is not { } entity)
            return;

        if (!_mind.TryGetMind(entity, out var mind, out _))
            return;

        if (!_goals.IsObservingContainer(mind, container.AsNullable()))
            return;

        Update();
    }

    private void OnObserverChanged(Entity<StellarGoalContainerObserverComponent> observer)
    {
        if (_player.LocalEntity is not { } entity)
            return;

        if (!_mind.TryGetMind(entity, out var mind, out _))
            return;

        if (mind != observer.Owner)
            return;

        Update();
    }

    private void LocalPlayerAttached(EntityUid obj)
    {
        Update();
    }

    protected override void Opened()
    {
        base.Opened();

        Update();
    }

    private void Update()
    {
        if (_player.LocalEntity is not { } entity)
            return;

        AttachedEntityView.SetEntity(entity);

        CharacterName.Text = Loc.GetString("stellar-character-window-name",
            ("name", _entity.GetComponent<MetaDataComponent>(entity).EntityName));

        if (!_mind.TryGetMind(entity, out var mind, out _))
            return;

        if (_job.MindTryGetJob(mind, out var job))
        {
            JobName.Text = Loc.GetString("stellar-character-window-job-name", ("job", job.LocalizedName));
            JobIcon.Texture = _sprite.Frame0(_prototype.Index(job.Icon).Icon);
            JobData.Visible = true;
        }
        else
        {
            JobData.Visible = false;
        }

        GoalContainer.RemoveAllChildren();
        foreach (var goal in _goals.GetGoals(mind))
        {
            GoalContainer.AddChild(new StellarGoalControl(goal));
        }
    }
}
