using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Humanoid;

// hack for a panel that modifies an entity's markings on demand

[GenerateTypedNameReferences]
public sealed partial class HumanoidMarkingModifierWindow : DefaultWindow
{
    public Action<MarkingSet>? OnMarkingAdded;
    public Action<MarkingSet>? OnMarkingRemoved;
    public Action<MarkingSet>? OnMarkingColorChange;
    public Action<MarkingSet>? OnMarkingRankChange;
    private readonly IPrototypeManager _protoMan = default!;

    public HumanoidMarkingModifierWindow()
    {
        RobustXamlLoader.Load(this);
        _protoMan = IoCManager.Resolve<IPrototypeManager>();

        MarkingPickerWidget.OnMarkingAdded += set => OnMarkingAdded!(set);
        MarkingPickerWidget.OnMarkingRemoved += set => OnMarkingRemoved!(set);
        MarkingPickerWidget.OnMarkingColorChange += set => OnMarkingColorChange!(set);
        MarkingPickerWidget.OnMarkingRankChange += set => OnMarkingRankChange!(set);
        MarkingForced.OnToggled += args => MarkingPickerWidget.Forced = args.Pressed;
        MarkingIgnoreSpecies.OnToggled += args => MarkingPickerWidget.Forced = args.Pressed;

        MarkingPickerWidget.Forced = MarkingForced.Pressed;
        MarkingPickerWidget.IgnoreSpecies = MarkingForced.Pressed;
    }

    public void SetState(
        MarkingSet markings,
        string species,
        Sex sex,
        Color skinColor
    )
    {
        var eyesColor = Color.White;

        MarkingPickerWidget.SetData(markings, species, sex, skinColor, eyesColor);
    }
}
