using Content.Shared.Goals;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Goals;

[GenerateTypedNameReferences]
public sealed partial class StellarGoalControl : PanelContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;
    private readonly StellarClientGoalsSystem _clientGoals;
    private readonly SpriteSystem _sprite;

    private readonly EntityUid _goal;

    public StellarGoalControl(Entity<StellarGoalComponent> goal)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _clientGoals = _entity.System<StellarClientGoalsSystem>();
        _sprite = _entity.System<SpriteSystem>();

        _goal = goal;

        Update(goal);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _clientGoals.OnGoalChanged += OnGoalChanged;
    }

    protected override void ExitedTree()
    {
        base.EnteredTree();

        _clientGoals.OnGoalChanged -= OnGoalChanged;
    }

    private void OnGoalChanged(Entity<StellarGoalComponent> ent)
    {
        if (ent.Owner != _goal)
            return;

        Update(ent);
    }

    private void Update(Entity<StellarGoalComponent> ent)
    {
        var metaData = _entity.GetComponent<MetaDataComponent>(ent);

        Title.Text = Loc.GetString("stellar-goal-title", ("title", metaData.EntityName));
        Description.Text = Loc.GetString("stellar-goal-description", ("description", metaData.EntityDescription));
        if (ent.Comp.Icon is { } icon)
            Icon.Texture = _sprite.Frame0(icon);

        PrimaryProgressBar.SetProgress((float)ent.Comp.Progress);
        SecondaryProgressBar.SetProgress((float)ent.Comp.Progress);
    }
}
